### PR TITLE
Support ZIP file download.

### PR DESCRIPTION
**Pull request by tft-kyrre**
Support for ZIP file download and import.
"Softpay" transactions are also fetched, but not imported.

### CODE REVIEW

**Review by tfk-kaare — COMMENTED** [review]
Ok, so I don't agree on temporary download of zip, extracting it, then re-archiving it before storing it to our disk.

What mobitech has done here is provide us with a finished zip. No need to mess with it.

My suggestion is to have a date check in both the `SinkMobitech::fetch()` and `::import()` methods that either download individual files, or the provided zip. If a zip is provided, fetch and store it as is.

I understand the structure of our stored zip will be different before and after a given date, but this is again up to the import() method to deal with.

Rename the `Mobitech::getData()` method to e.g. `::getChunkAsFiles()`, then add a new `getChunkAsZip()` which simply returns the archived version of the daily dump.

When importing the zip, utilizing the ChunkExtractor you get everything set up for import. It's just a matter of checking what directory structure the content has, based on the date flip.

What I'm saying here is: This can vastly be simplified by using stuff already provided.

**Comment by tft-kyrre** [comment]
It could be simplified even more if our `ChunkExtractor` had support for ZIP files with sub-folders, but it doesn't, so I opted for flattening the zip file content instead. An alternative would have been to traverse the zip file folders manually, but I assumed that having such code put in the import stage would be frowned upon.

ChunkExtractor can be easily fixed by having the `getFiles()` function return `$disk->allFiles()` instead of just `$disk->files()`. This means that no changes needs to be done to `SinkMobitech` nor `SinkImporter` and the downloaded zip file can be stored as it is.

**Comment by tfk-kaare** [comment]
Feel free to extend ragnarok-base with this functionality! I'd love to see this! :-)

**Comment by tft-kyrre** [comment]
Depends on [https://github.com/TromsFylkestrafikk/ragnarok-sink/pull/22](https://github.com/TromsFylkestrafikk/ragnarok-sink/pull/22)

**Comment by tft-kyrre** [comment]
The ZIP file from Mobitech also contains SoftPay transactions and this caused problems for the DB import, so I had to make some changes to the import code as well.

**Review by tfk-kaare — APPROVED** [review]
I'm fine with this. Only tested zip download, not the earlier by-the-thousands download method.

Zip is intact as created by mobitech, avoiding any added cause of errors. Great!

**Pull request merged**
